oe_virtual_assistant.settings:
  type: config_object
  label: 'Virtual Assistant Settings'
  mapping:
    backend_service_url:
      type: string
      label: 'Backend Service URL'
    token_issuer_url:
      type: string
      label: 'Token issuer URL'
