name: ci
on: [pull_request]
jobs:
  automated-tests:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: docker compose up -d
      - name: version
        run: docker compose exec -T web composer -v
      - name: build
        run: docker compose exec -T web composer install
      - name: wait-for-db
        run: sleep 10
      - name: test
        run: docker compose exec -T web ./vendor/bin/phpunit
  code-sniffer:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
      - run: docker compose up -d
      - name: build
        run: docker compose exec -T web composer install
      - name: test
        run: docker compose exec -T web ./vendor/bin/grumphp run
