name: CI
on: [pull_request]
jobs:
  automated-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php_version: ["8.2"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: clone
        uses: actions/checkout@v4
      - run: make
      - name: test
        # To avoid file permissions issues, we run the phpunit with user 33, which is the same as the apache user id container.
        run: docker compose exec -u 33 -T web phpunit
  code-sniffer:
    runs-on: ubuntu-24.04
    env:
      PHP_VERSION: "8.2"
    steps:
      - name: clone
        uses: actions/checkout@v4
      - run: make
      - name: test
        run: docker compose exec -T web grumphp run
